version: "3.9"
services:
  tailscale:
    build:
      context: images/tailscale
    environment:
      TAILSCALE_AUTH_KEY: ${TAILSCALE_AUTH_KEY:?err}
      TAILSCALE_HOSTNAME: ${TAILSCALE_HOSTNAME:-tailscale-docker-complex-example}
      TAILSCALE_STATE_ARG: "mem:"
  nginx:
    build:
      context: images/nginx
    depends_on:
      - service-one
      - service-two
    network_mode: "service:tailscale"
  service-one:
    image: nginxdemos/hello
  service-two:
    image: nginxdemos/hello
